version: '3.8'

services:
  # Servi√ßo da sua API Laravel
  app:
    build: .
    container_name: laravel_api
    restart: always
    ports:
      - "8000:80" # Acessa no navegador por localhost:8000
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=crud_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_crud
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"